### ISSUE TITLE
Alerts not reported

### ISSUE THREAD

**Issue by jazzyisj** [Pirate-Weather/pirateweather#118]
One feature I really miss from Dark Sky was detailed weather alerts from Environment Canada which don't seem to be reported in Pirate Weather.  The HA Environment Canada integration reports alerts and the title, but Dark Sky used to provide the whole description and beginning and end times for the alerts.

Any chance this could be added to Pirate Weather?

**Comment by cloneofghosts** [comment]
I know this is still on the roadmap but is there an updated timeline for when this may be added?

**Comment by alexander0042** [comment]
Still very much on the roadmap, but was focused on putting out fires with the v2 update and Time Machine data. This is high up on the list though!

**Comment by cloneofghosts** [comment]
@Marty-McFly73 Alerts are available in the US currently and are planned to be added to the API in the V2.6 or V2.7 update if you're located in Canada. If you're outside of those areas there isn't a timeline currently.

**Comment by cloneofghosts** [comment]
Just wanted to let everyone know that alerts have been added and will be available in the next API version. They are currently available on the development environment.

Regions don't work at the moment but should be fixed when moved to production.

**Comment by cloneofghosts** [comment]
Version 2.8 is now live with alerts! If you run into issues with alerts either reply or create a new issue and we can look into it.

**Comment by cloneofghosts** [comment]
I've done some testing with alerts and while it does work it seems some locations where there are alerts they aren't showing in the API. One location where this is true is Dijon, France.

There should be a Snow-ice warning but querying both the API and dev endpoint shows nothing. Testing with these coordinates: 47.31344,5.01391 in case that's helpful @alexander0042

**Comment by alexander0042** [comment]
It's due to an ingest issue- should be fixed in 2.8.3

**Comment by cloneofghosts** [comment]
It's been about an hour since 2.8.3 released and am still not seeing the alert. Does it take longer for alerts to ingest?

**Comment by alexander0042** [comment]
Shoot- it's also not throwing an error on the response, so it must be an ingest thing

**Comment by cloneofghosts** [comment]
If helpful here's two alerts that should be showing in the API which aren't. First one is the one in France which I mentioned and the other one is an Italian one which covers Milan.

[07-39995720e024962746976cbdafc71a4f.xml](https://github.com/user-attachments/files/23634546/07-39995720e024962746976cbdafc71a4f.xml)
[49-d0899b149ee9273d569ed762d735ce6e.xml](https://github.com/user-attachments/files/23634547/49-d0899b149ee9273d569ed762d735ce6e.xml)

**Comment by cloneofghosts** [comment]
@alexander0042 The alerts are being skipped because they have no polygon data. So ingest is working but they are being skipped because they lack polygon data.

**Comment by alexander0042** [comment]
Ahh, ok then. The fix in 2.8.3 was for locations in the UK, where they use the | symbol in the CAP feed, which was messing with things. From my light testing, it seemed like most of the CAP feeds contained regions, but clearly that's not always the case. The NWS alerts already has a parser I've built for this sort of conversion, which works well enough in the US, but that's it. 

I wonder if it'd be worth implementing this package: <https://github.com/NiklasJordan/meteoalarm>. Europe is big enough if I can get them all in one ingest, and then use WMO for the rest of the world

**Comment by cloneofghosts** [comment]
I also found this alert which has polygon data but I don't see it in the API? Maybe I'm just querying the wrong location?

[00-ee1f15913d1f17e17dad2d760d3b2cf7.xml](https://github.com/user-attachments/files/23637007/00-ee1f15913d1f17e17dad2d760d3b2cf7.xml)

Yeah, maybe it's worth looking into the meteoalarm for 2.9 to see if it would help things.

**Comment by cloneofghosts** [comment]
Version 2.8.4 fixes issues with European alerts not appearing in the API. There might be other ares which have geocodes that aren't supported at the moment. There is logging setup to determine which areas have unsupported geocodes but if you're missing alerts either reply to this issue or create a new one.
