### ISSUE TITLE
Rain/Snow Icon not Showing in Currently Section

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#29]
Did the threshold to show the precipitation icon on the currently block change? When I look at the API currently I see a precipIntensity of 0.36 so it should be showing snow as it's over the 0.25 threshold to show the snow icon. When I look in the hourly section it works like normal. My guess is that when you added the fallback to hourly data something messed up with the icon calculation in the HRRR domain?

Data from the API is below:

```
  "currently": {
    "time": 1677960000,
    "summary": "Cloudy",
    "icon": "cloudy",
    "nearestStormDistance": 0,
    "nearestStormBearing": 0,
    "precipIntensity": 0.36,
    "precipProbability": 0.25,
    "precipIntensityError": 0.0974,
    "precipType": "snow",
    "temperature": -0.03,
    "apparentTemperature": -1.95,
    "dewPoint": -1.09,
    "humidity": 0.93,
    "pressure": 998.9,
    "windSpeed": 5.736,
    "windGust": 12.15,
    "windBearing": 25.56,
    "cloudCover": 1.0,
    "uvIndex": 1.82,
    "visibility": 3.5,
    "ozone": 346.37
  },
...
    "hourly": {
    "summary": "Cloudy",
    "icon": "cloudy",
    "data": [
      {
        "time": 1677960000,
        "icon": "snow",
        "summary": "Snow",
        "precipIntensity": 0.2857,
        "precipProbability": 0.47,
        "precipIntensityError": 0.1053,
        "precipAccumulation": 0.2857,
        "precipType": "snow",
        "temperature": -0.02,
        "apparentTemperature": -1.95,
        "dewPoint": -1.09,
        "humidity": 0.93,
        "pressure": 998.9,
        "windSpeed": 5.74,
        "windGust": 12.15,
        "windBearing": 25.56,
        "cloudCover": 1.0,
        "uvIndex": 1.82,
        "visibility": 3.5,
        "ozone": 346.37
      },
```

**Comment by alexander0042** [comment]
Great catch, and sorry I didn't get to it sooner. It turned out to be a rounding problem, which spiraled into the icon selection logic. Fixed in v1.4.1, and changelog is updated!

**Comment by cloneofghosts** [comment]
@alexander0042 Thanks for the update but it doesn't appear to be fixed. I see the following when I query the API and it is still showing cloudy.

```
  "currently": {
    "time": 1678725780,
    "summary": "Cloudy",
    "icon": "cloudy",
    "precipIntensity": 0.4395,
    "precipProbability": 0.94,
    "precipIntensityError": 0.033,
    "precipType": "snow",
  },
  ```

**Comment by alexander0042** [comment]
Shoot! It was literally just working, but evidently not! Let me check on this

**Comment by cloneofghosts** [comment]
@alexander0042 It appears that the currently section is pulling in the precipIntensity from the minutely section? I bet the current precipIntensity is 0 which is why the cloudy icon is being shown instead of snow?

**Comment by alexander0042** [comment]
Great catch! That's the idea- it doesn't pull directly from the minutely section because I'm working on optimizing the code so I can avoid processing things when they're not needed. In this case it was an issue of me hitting the wrong deploy button, so at least an easy fix. 

I think I have it all working now- snow in Ottawa is set to start in about 30 minutes, so I'll check then to verify.

**Comment by alexander0042** [comment]
Had to go looking for snow somewhere, but this seems to work: `47.43,-74.93,1678732140`. You'll notice that it varies slightly from the minutely values, and I should add this to the docs I guess. Minutely is based on the interpolated values, while the currently is just the closest time. Theoretically I suppose interpolated values might be more accurate; however, I like the simplicity of using the raw model result, since it provides a really nice check that everything is working

**Comment by cloneofghosts** [comment]
Was just about to post that I found a place which is showing the precipitation icon. I used 45.512230,-122.658722 which is showing the rain icon.

I noticed that precipitationIntensity is no longer rounded to two decimal points anymore on the currently block like it was before. The issue about fixing rounding is still open so it might be worth just fixing all of them at once?

**Comment by alexander0042** [comment]
Big fan of "all at once", and it's set to 2 decimal places now!

**Comment by cloneofghosts** [comment]
Thanks! I also double checked a location outside of the HRRR domain to make sure that it was being rounded there and it is.

Since everything is fixed I'm going to close this issue now.

**Comment by cloneofghosts** [comment]
@alexander0042 I haven't confirmed this for myself but it seems like precipIntensities below 0.44 don't show up in the currently block when I've seen precipIntensity above 0 in the minutely block (I know you said its interpolated).

Outside of the HRRR domain all precipItensity values show no matter if it's enough to trigger the icon or not so is it just a bug in the HRRR domain? If so can you set it to be like GFS where all values show no matter ifs above the threshold to show the icon.

**Comment by cloneofghosts** [comment]
@alexander0042 Has this been looked into at all? I think this was around the time you were either working on the text summaries or Kong so it might have been missed.

**Comment by cloneofghosts** [comment]
@alexander0042 I noticed an oddity when looking at my HA install. I noticed that Thursday the icon is showing rain but Saturday is showing cloudy. Looking at the daily blocks I see the following:

Thursday:
```
      {
        "time": 1688616000,
        "icon": "rain",
        "summary": "Rain",
        "sunriseTime": 1688635338,
        "sunsetTime": 1688691161,
        "moonPhase": 0.6153030844349172,
        "precipIntensity": 0.0256,
        "precipIntensityMax": 0.1831,
        "precipIntensityMaxTime": 1688695200,
        "precipProbability": 0.123,
        "precipAccumulation": 0.0588,
        "precipType": "rain",
        "temperatureHigh": 32.79,
        "temperatureHighTime": 1688670000,
        "temperatureLow": 21.29,
        "temperatureLowTime": 1688716800,
        "apparentTemperatureHigh": 37.85,
        "apparentTemperatureHighTime": 1688666400,
        "apparentTemperatureLow": 27.02,
        "apparentTemperatureLowTime": 1688716800,
        "dewPoint": 18.08,
        "humidity": 0.611,
        "pressure": 1001.67,
        "windSpeed": 10.3,
        "windGust": 20.4,
        "windGustTime": 1688677200,
        "windBearing": 201.7,
        "cloudCover": 0.639,
        "uvIndex": 7.71,
        "uvIndexTime": 1688662800,
        "visibility": 16.09,
        "temperatureMin": 20.23,
        "temperatureMinTime": 1688634000,
        "temperatureMax": 33.16,
        "temperatureMaxTime": 1688677200,
        "apparentTemperatureMin": 27.02,
        "apparentTemperatureMinTime": 1688634000,
        "apparentTemperatureMax": 37.85,
        "apparentTemperatureMaxTime": 1688666400
      },
```

Saturday:
```
      {
        "time": 1688788800,
        "icon": "cloudy",
        "summary": "Cloudy",
        "sunriseTime": 1688808225,
        "sunsetTime": 1688863909,
        "moonPhase": 0.6931086499146522,
        "precipIntensity": 0.0368,
        "precipIntensityMax": 0.1066,
        "precipIntensityMaxTime": 1688839200,
        "precipProbability": 0.181,
        "precipAccumulation": 0.0847,
        "precipType": "rain",
        "temperatureHigh": 25.18,
        "temperatureHighTime": 1688842800,
        "temperatureLow": 16.12,
        "temperatureLowTime": 1688889600,
        "apparentTemperatureHigh": 30.44,
        "apparentTemperatureHighTime": 1688832000,
        "apparentTemperatureLow": 22.12,
        "apparentTemperatureLowTime": 1688889600,
        "dewPoint": 16.46,
        "humidity": 0.76,
        "pressure": 999.25,
        "windSpeed": 8.34,
        "windGust": 12.88,
        "windGustTime": 1688860800,
        "windBearing": 188.88,
        "cloudCover": 0.911,
        "uvIndex": 5.83,
        "uvIndexTime": 1688832000,
        "visibility": 16.09,
        "temperatureMin": 17.36,
        "temperatureMinTime": 1688806800,
        "temperatureMax": 25.18,
        "temperatureMaxTime": 1688842800,
        "apparentTemperatureMin": 22.12,
        "apparentTemperatureMinTime": 1688806800,
        "apparentTemperatureMax": 30.44,
        "apparentTemperatureMaxTime": 1688832000
      },
```

Looking at the documentation it says that in order for the rain icon to show it needs to have an accumulation of 1mm or more with a probability of 30% or higher in any hour. Thursday has an accumulation of 0.588mm and Saturday is 0.847mm. As neither of them reach the 1mm accumulation threshold neither of them should show the rain icon but Thursday is and Saturday isn't for some reason.

**Comment by cloneofghosts** [comment]
The bug I posted about last March seems to be fixed? It could just be a case of the model rarely reporting intensities lower than 0.44 mm/h

**Comment by alexander0042** [comment]
Thanks for closing! This one is fixed (or at least should be), but I forgot to ping back here

**Comment by cloneofghosts** [comment]
@alexander0042 Am seeing this again even with reflectivity. It's been snowing for a few hours and the API hasn't shown snow. At 8:30am this morning the API was showing snow within the next hour but it disappeared and never came back.

I took a look earlier at the sub-hourly HRRR and the reflectivity is showing no snow for Ottawa which is likely why it isn't showing any snow. Hopefully RRFS/3DRTMA are better in this regard?

**Comment by cloneofghosts** [comment]
@alexander0042 Re-opening this issue as am still seeing this happening even with the switch to reflectivity. I've added an image of the composite reflectivity (I think this is what PW uses?)

<img width="636" height="625" alt="Image" src="https://github.com/user-attachments/assets/100841d2-9259-446f-8792-b7336fa98042" />

Minutely summary shows: Mostly cloudy for the hour. which is incorrect as its snowing at the moment and will continue to do so for the next few hours.
